# explanation of break and continue statements with some hard examples in loops
#  the break statement is used to exit a loop prematurely when a certain condition is met
#  the continue statement is used to skip the current iteration of a loop and move on to the next iteration
#  example of using break statement in a for loop   
for i in range(10):
    if i == 5:
        break
    print(i)    
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 9 and print each number until it reaches 5, at which point the break statement will exit the loop
#  the output will be:  0 1 2 3 4
#  example of using continue statement in a for loop
for i in range(10):
    if i % 2 == 0:
        continue
    print(i)    
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 9 and print each odd number while skipping the even numbers using the continue statement
#  the output will be:  1 3 5 7 9   
#  example of using break statement in a while loop
i = 0   
while i < 10:
    if i == 5:
        break
    print(i)
    i += 1  
#  in the above example, the while loop will execute the block of code as long as the condition i < 10 is true and print each number until it reaches 5, at which point the break statement will exit the loop
#  the output will be:  0 1 2 3 4
#  example of using continue statement in a while loop
i = 0   
while i < 10:
    if i % 2 == 0:
        i += 1
        continue
    print(i)
    i += 1  
#  in the above example, the while loop will execute the block of code as long as the condition i < 10 is true and print each odd number while skipping the even numbers using the continue statement
#  the output will be:  1 3 5 7 9
#  you can also use the break and continue statements in nested loops
for i in range(3):
    for j in range(3):
        if i == 1 and j == 1:
            break
        print(f"i: {i}, j: {j}")    
#  in the above example, the outer loop will iterate 3 times and the inner loop will iterate 3 times for each iteration of the outer loop, but when i is 1 and j is 1, the break statement will exit the inner loop and move on to the next iteration of the outer loop
#  the output will be:
#  i: 0, j: 0   
#  i: 0, j: 1
#  i: 0, j: 2
#  i: 1, j: 0
#  i: 2, j: 0
#  you can also use the continue statement in nested loops to skip certain iterations
for i in range(3):  
    for j in range(3):
        if i == 1 and j == 1:
            continue
        print(f"i: {i}, j: {j}")    
#  in the above example, the outer loop will iterate 3 times and the inner loop will iterate 3 times for each iteration of the outer loop, but when i is 1 and j is 1, the continue statement will skip that iteration and move on to the next iteration of the inner loop
#  the output will be:  
#  i: 0, j: 0
#  i: 0, j: 1
#  i: 0, j: 2
#  i: 1, j: 0
#  i: 1, j: 2
#  i: 2, j: 0
#  you can also use the break and continue statements in a for loop with an else clause
for i in range(5):
    if i == 3:
        break
    print(i)
else:
    print("Loop completed without break")
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 4 and print each number until it reaches 3, at which point the break statement will exit the loop and the else clause will not be executed
#  the output will be:  0 1 2
#  if you change the condition in the if statement to a number that is not in therange, the loop will complete without hitting the break statement and the else clause will be executed
for i in range(5):
    if i == 10:
        break
    print(i)
else:
    print("Loop completed without break")
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 4 and print each number without hitting the break statement, so the else clause will be executed
#  the output will be:  0 1 2 3 4
#  you can also use the break and continue statements in a while loop with an else clause
i = 0
while i < 5:
    if i == 3:
        break
    print(i)
    i += 1
else:
    print("Loop completed without break")
#  in the above example, the while loop will execute the block of code as long as the condition i < 5 is true and print each number until it reaches 3, at which point the break statement will exit the loop and the else clause will not be executed
#  the output will be:  0 1 2
#  if you change the condition in the if statement to a number that is not less than 5, the loop will complete without hitting the break statement and the else clause will be executed
i = 0   
while i < 5:
    if i == 10:
        break
    print(i)
    i += 1  
else:
    print("Loop completed without break")
#  in the above example, the while loop will execute the block of code as long as the condition i < 5 is true and print each number without hitting the break statement, so the else clause will be executed
#  the output will be:  0 1 2 3 4   
    
