# intro to range function and how to use it in loops with expanations and examples
#  the range() function is used to generate a sequence of numbers
#  the syntax of the range() function is:   
#  range(start, stop, step)
#  start: the starting number of the sequence (default is 0)    
#  stop: the ending number of the sequence (required)
#  step: the increment between each number in the sequence (default is 1)
#  example of using range() function in a for loop
for i in range(5):
    print(i)    
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 4 (5 is not included) and print each number
#  the output will be:  0 1 2 3 4
#  you can also specify the starting number and the increment in the range() function
for i in range(1, 10, 2):
    print(i)    
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 1 to 9 (10 is not included) with an increment of 2 and print each number
#  the output will be:  1 3 5 7 9   
#  you can also use the range() function to iterate over a list or a string by using the length of the list or string as the stop parameter
fruits = ["apple", "banana", "cherry"]
for i in range(len(fruits)):
    print(fruits[i])    
#  in the above example, the for loop will iterate over the sequence of numbers generated by the range() function, which is from 0 to 2 (3 is not included) and print each fruit in the list using its index
#  the output will be:  apple banana cherry 
#  you can also use the range() function to create a list of numbers by converting the range object to a list
numbers = list(range(5))
print(numbers)
#  in the above example, the range() function will generate a sequence of numbers from
#  0 to 4 (5 is not included) and the list() function will convert the range object to a list
#  the output will be:  [0, 1, 2, 3, 4]
#  you can also use the range() function to create a list of numbers with a specific starting number and increment
even_numbers = list(range(0, 20, 2))
print(even_numbers)
#  in the above example, the range() function will generate a sequence of even numbers from 0 to 18 (20 is not included) with an increment of 2 and the list() function will convert the range object to a list
#  the output will be:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
#  you can also use the range() function to create a list of numbers in reverse order by using a negative increment
reverse_numbers = list(range(10, 0, -1))    
print(reverse_numbers)
#  in the above example, the range() function will generate a sequence of numbers from 10 to 1 (0 is not included) with a negative increment of -1 and the list() function will convert the range object to a list
#  the output will be:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
#  you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter
#  the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with an increment of 1
#  example of using range() function to create a list of numbers with a specific starting number and ending number
#   the range() function will generate a sequence of numbers from 1 to 10 (11 is not included) with an increment of 1 and the list() function will convert the range object to a list
numbers = list(range(1, 11))
print(numbers)  
# the output will be:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter and a negative increment
# the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with a negative increment of -1
reverse_numbers = list(range(10, 0, -1))
print(reverse_numbers)
# the output will be:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]  
# you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter and a positive increment
# the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with a positive increment of 2
even_numbers = list(range(0, 20, 2))    
print(even_numbers)
# the output will be:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
# you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter and a positive increment
# the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with a positive increment of 3
multiples_of_three = list(range(0, 30, 3))
print(multiples_of_three)
# the output will be:  [0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
# you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter and a negative increment
# the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with a negative increment of -2
reverse_even_numbers = list(range(20, 0, -2))
print(reverse_even_numbers)
# the output will be:  [20, 18, 16, 14, 12, 10, 8, 6, 4, 2]
# you can also use the range() function to create a list of numbers with a specific starting number and ending number by using the stop parameter and a negative increment
# the range() function will generate a sequence of numbers from the starting number to the ending number (stop is not included) with a negative increment of -3
reverse_multiples_of_three = list(range(30, 0, -3))
print(reverse_multiples_of_three)
# the output will be:  [30, 27, 24, 21,18, 15, 12, 9, 6, 3]  
